type Message={role:"system"|"user"|"assistant";content:string};
type ApiMode="responses"|"chat_completions"|"chat_completions_prompt_json";
type Options={model:string;apiUrl?:string;apiKey?:string;apiMode?:ApiMode;maxTokens?:number;timeoutMs?:number;jsonSchema?:{name:string;schema:Record<string,unknown>};requestIdempotencyKey?:string;[key:string]:unknown};
function responseText(json:any){if(typeof json.output_text==="string")return json.output_text;for(const item of json.output||[])for(const content of item.content||[])if(typeof content.text==="string")return content.text;return "";}
function chatText(json:any){const c=json?.choices?.[0]?.message?.content;return typeof c==="string"?c:"";}
function endpoint(base:string,mode:ApiMode){const b=base.replace(/\/$/,"");if(mode==="responses")return b.endsWith("/responses")?b:`${b}/responses`;return b.endsWith("/chat/completions")?b:`${b}/chat/completions`;}
export async function callNexMindDetailed(messages:Message[],options:Options){
 const apiKey=String(options.apiKey||"").trim();const base=String(options.apiUrl||"").trim();const mode=(options.apiMode||((options.forceResponsesTransport||options.responsesApi)?"responses":"chat_completions")) as ApiMode;
 if(!apiKey)throw new Error("NEXMIND_PROVIDER_CREDENTIAL_MISSING");if(!base)throw new Error("NEXMIND_PROVIDER_BASE_URL_MISSING");if(!options.model)throw new Error("NEXMIND_PROVIDER_MODEL_MISSING");
 const headers:Record<string,string>={authorization:`Bearer ${apiKey}`,"content-type":"application/json"};if(options.requestIdempotencyKey)headers["Idempotency-Key"]=options.requestIdempotencyKey;
 let body:any;
 if(mode==="responses"){const input=messages.map(m=>({role:m.role,content:[{type:"input_text",text:m.content}]}));body={model:options.model,input,max_output_tokens:options.maxTokens??700};if(options.jsonSchema)body.text={format:{type:"json_schema",name:options.jsonSchema.name,schema:options.jsonSchema.schema,strict:true},verbosity:"low"};}
 else {let outMessages=[...messages];body={model:options.model,messages:outMessages,max_tokens:options.maxTokens??700};if(options.jsonSchema&&mode==="chat_completions")body.response_format={type:"json_schema",json_schema:{name:options.jsonSchema.name,schema:options.jsonSchema.schema,strict:true}};if(options.jsonSchema&&mode==="chat_completions_prompt_json")body.messages=[{role:"system",content:`Return ONLY JSON matching this schema exactly. No markdown.\n${JSON.stringify(options.jsonSchema.schema)}`},...outMessages];}
 const response=await fetch(endpoint(base,mode),{method:"POST",headers,body:JSON.stringify(body),signal:AbortSignal.timeout(options.timeoutMs??12000)});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`NEXMIND_PROVIDER_REQUEST_FAILED (${response.status}): ${JSON.stringify(json).slice(0,500)}`);return{content:mode==="responses"?responseText(json):chatText(json),providerRequestId:response.headers.get("x-request-id")||json.id||null,usage:json.usage||null};}
export function parseProviderJson(value:string){const trimmed=value.trim();try{return JSON.parse(trimmed);}catch{const m=trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);if(m)return JSON.parse(m[1]);throw new Error("Provider did not return valid JSON.");}}
