import { appendAuditEvent } from "@/lib/audit-log";
import { requireSession } from "@/lib/route-auth";
import { json, problem } from "@/lib/http";
import { getPrisma } from "@/lib/db";
import { env } from "@/lib/env";
import { inspectUpload, quarantineObjectKey, safeUploadName } from "@/lib/upload-security";
import { writeObject } from "@/lib/object-storage";
import { consumeRateLimit } from "@/lib/rate-limit";
export const runtime = "nodejs";
function assetKind(mime: string | null, name: string | null) {const value = `${mime ?? ""} ${name ?? ""}`.toLowerCase();if (value.includes("logo")) return "logo";if (value.startsWith("image/")) return "image";if (value.startsWith("video/")) return "video";if (value.startsWith("audio/")) return "audio";if (value.includes("json") || value.includes("csv")) return "data";if (value.includes("pdf") || value.includes("text/")) return "document";return "other";}
export async function GET(request: Request) {const auth = await requireSession(request); if (auth.response) return auth.response;const rows = await getPrisma()!.source.findMany({ where: { ownerUserId: auth.session!.userId, isReusable: true }, orderBy: { updatedAt: "desc" }, take: 100 });return json({ items: rows.map((row) => ({id: row.id, name: row.name || "Saved source", kind: assetKind(row.mimeType, row.name), mimeType: row.mimeType,sizeBytes: row.sizeBytes == null ? null : Number(row.sizeBytes), reusable: row.isReusable,rightsAttested: row.rights && typeof row.rights === "object" && !Array.isArray(row.rights) ? Boolean((row.rights as Record<string, unknown>).attested) : null,status: row.status === "READY" ? "ready" : row.status === "FAILED" || row.status === "BLOCKED" ? "failed" : "processing",securityStatus:(row as {securityStatus?:string}).securityStatus??"UNKNOWN",previewUrl: row.status === "READY" && (row as {securityStatus?:string}).securityStatus === "CLEAN" && ["image","logo","video"].includes(assetKind(row.mimeType, row.name)) ? `/api/v1/studio/assets/${row.id}/content` : null, sourceProductionId: null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(),})), nextCursor: null }, auth.id);}
export async function POST(request:Request){
  const auth=await requireSession(request);if(auth.response)return auth.response;const limit=await consumeRateLimit(auth.session!.userId,"asset_upload",20,3600000);if(!limit.allowed)return problem(auth.id,429,"UPLOAD_RATE_LIMITED","Too many uploads",`Wait ${limit.retryAfterSeconds} seconds.`);const length=Number(request.headers.get("content-length")||0);if(length>env.uploadMaxBytes+1024*1024)return problem(auth.id,413,"UPLOAD_TOO_LARGE","File is too large",`Uploads are limited to ${Math.floor(env.uploadMaxBytes/1024/1024)} MB.`);
  const form=await request.formData().catch(()=>null);const value=form?.get("file");if(form?.get("rightsAttested")!=="true")return problem(auth.id,422,"UPLOAD_RIGHTS_ATTESTATION_REQUIRED","Confirm you can use this file","Studio requires a rights attestation before accepting uploaded source material.");if(!(value instanceof File))return problem(auth.id,422,"UPLOAD_FILE_REQUIRED","Choose a file","Attach one supported Studio source file.");if(value.size>env.uploadMaxBytes)return problem(auth.id,413,"UPLOAD_TOO_LARGE","File is too large",`Uploads are limited to ${Math.floor(env.uploadMaxBytes/1024/1024)} MB.`);
  const bytes=new Uint8Array(await value.arrayBuffer());let inspected;try{inspected=inspectUpload(bytes,value.type||null);}catch(error){const code=error instanceof Error?error.message:"UPLOAD_REJECTED";await appendAuditEvent({request,requestId:auth.id,actorUserId:auth.session!.userId,action:"UPLOAD_REJECTED",entityType:"Source",entityId:"pending",after:{code,sizeBytes:value.size}});return problem(auth.id,422,code,"File could not be accepted","Use a supported, non-encrypted file without active content.");}
  const prisma=getPrisma()!;const name=safeUploadName(value.name);const quarantineKey=quarantineObjectKey(auth.session!.userId,name);await writeObject(quarantineKey,bytes,{contentType:inspected.detectedMime});
  const source=await prisma.source.create({data:{ownerUserId:auth.session!.userId,name,kind:"FILE",objectKey:null,quarantineObjectKey:quarantineKey,mimeType:value.type||inspected.detectedMime,detectedMimeType:inspected.detectedMime,sizeBytes:BigInt(value.size),isReusable:true,rights:{attested:true,source:"user_upload"},contentHash:inspected.contentHash,status:"ANALYSING",securityStatus:"QUARANTINED",uploadScanJob:{create:{status:"QUEUED",scanner:"CLAMAV"}}}});
  await appendAuditEvent({request,requestId:auth.id,actorUserId:auth.session!.userId,action:"UPLOAD_QUARANTINED",entityType:"Source",entityId:source.id,after:{detectedMimeType:inspected.detectedMime,sizeBytes:value.size,contentHash:inspected.contentHash}});
  return json({id:source.id,status:"processing",name:source.name,mimeType:inspected.detectedMime},auth.id,{status:202});
}
