import { json, problem, zodProblem } from "@/lib/http";
import { isProductionOperator } from "@/lib/roles";
import { requireSession, requireTrustedOrigin } from "@/lib/route-auth";
import { assembleP8MultimodalReviewPackage, p8MultimodalPackageInputSchema } from "@/studio-v1/nexmind-p8/multimodal-evidence";

export const runtime = "nodejs";

export async function POST(request: Request, context: { params: Promise<{ productionId: string }> }) {
  const auth = await requireSession(request); if (auth.response) return auth.response;
  if (!isProductionOperator(auth.session.user)) return problem(auth.id, 403, "PRODUCTION_OPERATOR_REQUIRED", "Production operator access required", "Use the verified internal production-review account.");
  const originError = requireTrustedOrigin(request, auth.id); if (originError) return originError;
  const { productionId } = await context.params;
  const parsed = p8MultimodalPackageInputSchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return zodProblem(auth.id, parsed.error);
  try {
    const artifact = await assembleP8MultimodalReviewPackage({ productionId, operatorUserId: auth.session.userId, requestId: auth.id, body: parsed.data });
    return json({ artifactId: artifact.id, contentHash: artifact.contentHash, status: "COMPLETE" }, auth.id, { status: 201 });
  } catch (error) {
    const code = error instanceof Error ? error.message : "MULTIMODAL_PACKAGE_FAILED";
    if (code === "PRODUCTION_NOT_FOUND" || code === "STUDIO_WORKFLOW_NOT_FOUND" || code === "MULTIMODAL_ARTIFACT_NOT_FOUND") return problem(auth.id, 404, code, "Review evidence not found", "Use artifacts generated by this exact production.");
    if (code.startsWith("NEXMIND_") || code.startsWith("MULTIMODAL_")) return problem(auth.id, 409, code.split(":", 1)[0], "Review evidence is not ready", "The Studio must generate and bind the internal visual/audio review evidence before this package can be certified.");
    console.error("Multimodal review package assembly failed", error);
    return problem(auth.id, 500, "MULTIMODAL_PACKAGE_FAILED", "Review package could not be assembled", "The paid production remains intact.");
  }
}
