import { z } from "zod";
import { appendAuditEvent } from "@/lib/audit-log";
import { getPrisma } from "@/lib/db";
import { json, problem, zodProblem } from "@/lib/http";
import { retrieveFundingCheckout } from "@/lib/payment-provider";
import { requireSession } from "@/lib/route-auth";
import { settleStandaloneFundingIntent } from "@/studio-v1/billing";
export const runtime="nodejs";
const schema=z.object({sessionId:z.string().min(8).max(255)}).strict();
export async function POST(request:Request){const auth=await requireSession(request);if(auth.response)return auth.response;const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return zodProblem(auth.id,parsed.error);const intent=await getPrisma()!.studioFundingIntent.findFirst({where:{userId:auth.session!.userId,provider:"stripe",providerReference:parsed.data.sessionId}});if(!intent)return problem(auth.id,404,"FUNDING_INTENT_NOT_FOUND","Funding attempt not found","Return to your saved production.");try{const session=await retrieveFundingCheckout(parsed.data.sessionId);if(session.client_reference_id!==intent.id||session.metadata?.funding_intent_id!==intent.id)return problem(auth.id,409,"FUNDING_PROVIDER_REFERENCE_MISMATCH","Funding could not be reconciled","The payment reference does not match this Studio funding attempt.");if(session.payment_status!=="paid")return json({fundingIntentId:intent.id,status:intent.status,paid:false,productionId:intent.productionId},auth.id);if(typeof session.amount_total!=="number"||!session.currency)return problem(auth.id,409,"FUNDING_SETTLEMENT_MISMATCH","Funding could not be reconciled","The provider amount is incomplete.");const result=await settleStandaloneFundingIntent({fundingIntentId:intent.id,providerReference:session.id,amountMinor:session.amount_total,currency:session.currency});await appendAuditEvent({request,requestId:auth.id,actorUserId:auth.session!.userId,action:"FUNDING_RECONCILED",entityType:"StudioFundingIntent",entityId:intent.id,after:{reused:result.reused,amountMinor:intent.amountMinor,currency:"USD"}});return json({fundingIntentId:intent.id,status:"SETTLED",paid:true,productionId:intent.productionId},auth.id);}catch(error){console.error("Funding reconciliation failed",error);return problem(auth.id,503,"FUNDING_RECONCILIATION_FAILED","Payment confirmation is still pending","Do not pay again. Return to this same production and retry confirmation.");}}
