import { json, problem, zodProblem } from "@/lib/http";
import { isProductionOperator } from "@/lib/roles";
import { idempotencyKey, requireSession, requireTrustedOrigin } from "@/lib/route-auth";
import { p8HumanReviewInputSchema, recordP8BlindHumanReview } from "@/studio-v1/nexmind-p8/human-review";
import { queueStandaloneNexMindP8Finalize } from "@/studio-v1/nexmind-p8/workflow";

export const runtime = "nodejs";

export async function POST(request: Request, context: { params: Promise<{ productionId: string }> }) {
  const auth = await requireSession(request); if (auth.response) return auth.response;
  if (!isProductionOperator(auth.session.user)) return problem(auth.id, 403, "PRODUCTION_OPERATOR_REQUIRED", "Production operator access required", "Use the verified internal production-review account.");
  const originError = requireTrustedOrigin(request, auth.id); if (originError) return originError;
  const key = idempotencyKey(request, auth.id); if (key.response) return key.response;
  const { productionId } = await context.params;
  const parsed = p8HumanReviewInputSchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return zodProblem(auth.id, parsed.error);
  try {
    const result = await recordP8BlindHumanReview({ operatorUserId: auth.session.userId, productionId, requestId: auth.id, idempotencyKey: key.value!, body: parsed.data });
    const finalizeActivity = result.gate.status === "PASS" ? await queueStandaloneNexMindP8Finalize(productionId) : null;
    return json({ ...result, finalizeActivityId: finalizeActivity?.id ?? null, finalizeQueued: Boolean(finalizeActivity) }, auth.id, { status: 201 });
  } catch (error) {
    const code = error instanceof Error ? error.message : "NEXMIND_REVIEW_FAILED";
    if (code === "PRODUCTION_NOT_FOUND" || code === "REVIEW_ARTIFACT_NOT_FOUND") return problem(auth.id, 404, code, "Review target not found", "Use the exact production review package generated by the Studio.");
    if (code === "REVIEWER_NOT_INDEPENDENT") return problem(auth.id, 409, code, "Independent reviewer required", "The production owner cannot certify the Studio's internal blind review.");
    if (code === "REVIEW_ARTIFACT_HASH_MISMATCH" || code === "REVIEW_ARTIFACT_TYPE_INVALID") return problem(auth.id, 409, code, "Review evidence does not match", "Review only the exact hashed multimodal package generated for this production.");
    console.error("NexMind P8 blind review record failed", error);
    return problem(auth.id, 500, "NEXMIND_REVIEW_FAILED", "Internal review could not be recorded", "The paid production remains intact. Retry the same review with the same idempotency key.");
  }
}
