import { randomUUID } from "node:crypto";
import { z } from "zod";
import { requireSession, requireTrustedOrigin } from "@/lib/route-auth";
import { getPrisma } from "@/lib/db";
import { json, problem, zodProblem } from "@/lib/http";
import { ProductionDraftService } from "@/lib/studio-production-draft-core";
import { PrismaProductionDraftRepository } from "@/lib/studio-production-draft-repository";
import { syncClaimedDraftToCanonicalProduction } from "@/studio-v1/architecture/core";
import { getVideoType, PRODUCTION_REGISTRY } from "@/studio-v1/public/registry";
export const runtime="nodejs";
const schema=z.object({family:z.enum(["EXPLAINER","WHITEBOARD","STICKMAN","EDITORIAL_MOTION"]),videoType:z.string().trim().min(1).max(120),prompt:z.string().trim().min(1).max(20_000),duration:z.number().int().min(1).max(86_400).nullable().optional(),aspectRatio:z.enum(["16:9","9:16","1:1"]).nullable().optional()});
const FAMILY_ID={EXPLAINER:"explainer",WHITEBOARD:"whiteboard",STICKMAN:"stickman",EDITORIAL_MOTION:"editorial-motion"} as const;
export async function POST(request:Request,context:{params:Promise<{id:string}>}){
 const auth=await requireSession(request);if(auth.response)return auth.response;const origin=requireTrustedOrigin(request,auth.id);if(origin)return origin;const body=schema.safeParse(await request.json().catch(()=>null));if(!body.success)return zodProblem(auth.id,body.error);const{id}=await context.params;const prisma=getPrisma()!;const series=await prisma.studioSeries.findFirst({where:{id,ownerUserId:auth.session!.userId}});if(!series)return problem(auth.id,404,"SERIES_NOT_FOUND","Series not found","No production was created.");const type=getVideoType(PRODUCTION_REGISTRY,body.data.videoType);if(!type||type.family!==FAMILY_ID[body.data.family]||!type.publicEnabled||type.capabilityContract.verification.status!=="verified")return problem(auth.id,409,"PRODUCTION_TYPE_NOT_PUBLIC","Production type unavailable","Choose a currently certified public production type.");
 const service=new ProductionDraftService(new PrismaProductionDraftRepository());const productionId=randomUUID();let draft;try{draft=await service.ensure({id:productionId,family:body.data.family,videoType:body.data.videoType,prompt:body.data.prompt,sources:[],duration:body.data.duration??null,aspectRatio:body.data.aspectRatio??null,voicePreference:null,brandContext:null},{kind:"USER",userId:auth.session!.userId});await syncClaimedDraftToCanonicalProduction(draft);}catch(error){return problem(auth.id,409,"NEXT_EPISODE_DRAFT_FAILED","Next episode could not be created",error instanceof Error?error.message:"The production draft could not be created.");}
 for(let attempt=0;attempt<4;attempt+=1){try{const result=await prisma.$transaction(async(tx)=>{const fresh=await tx.studioSeries.findFirst({where:{id,ownerUserId:auth.session!.userId}});if(!fresh)throw new Error("SERIES_NOT_FOUND");const max=await tx.studioSeriesEpisode.aggregate({where:{seriesId:id},_max:{episodeOrdinal:true}});const episodeOrdinal=(max._max.episodeOrdinal??0)+1;await tx.production.update({where:{id:productionId},data:{seriesId:id,brandId:fresh.brandId}});const episode=await tx.studioSeriesEpisode.create({data:{seriesId:id,productionId,episodeOrdinal,title:body.data.prompt.slice(0,120)}});return episode;},{isolationLevel:"Serializable"});return json({productionId,seriesId:id,episodeOrdinal:result.episodeOrdinal,brandId:series.brandId},auth.id,{status:201});}catch(error){const code=String((error as {code?:string}).code??"");if((code==="P2002"||code==="P2034")&&attempt<3)continue;return problem(auth.id,409,"NEXT_EPISODE_BIND_FAILED","Next episode could not be bound to the Series","The production was preserved as a draft; Series continuity was not partially changed.");}}
 return problem(auth.id,409,"NEXT_EPISODE_BIND_RETRY_EXHAUSTED","Next episode could not be created","Retry from the Series desk.");
}
