import { useEffect, useState } from "react";
import { useStudioAssets, useStudioBrands, useStudioCast } from "../hooks.js";
import { studioMutation } from "../api.js";
import { ErrorState, LoadState } from "./shared.js";
import { MemoryPanel } from "./MemoryPanel.js";

function FilesView() {
  const assets = useStudioAssets();
  if (assets.loading) return <LoadState label="Loading files"/>;
  if (assets.error) return <ErrorState message={assets.error} onRetry={assets.refresh}/>;
  const items = assets.data?.items ?? [];
  return items.length ? <div className="sf-assets-grid">{items.map((asset) => <article key={asset.id}><div className={`sf-asset-preview sf-asset-${asset.kind}`}>{asset.previewUrl && (asset.kind === "image" || asset.kind === "logo") ? <img src={asset.previewUrl} alt=""/> : asset.previewUrl && asset.kind === "video" ? <video src={asset.previewUrl} muted playsInline preload="metadata"/> : <span>{asset.kind}</span>}</div><div><small>{asset.status}</small><b>{asset.name}</b><p>{asset.reusable ? "Reusable" : "Production only"}{asset.rightsAttested === false ? " · rights need review" : ""}</p></div></article>)}</div> : <div className="sf-empty"><h2>No reusable files yet.</h2><p>Only files actually saved to your account appear here.</p></div>;
}

function CastView() {
  const cast = useStudioCast(); const brands = useStudioBrands();
  const [selectedId, setSelectedId] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ name:"", brandId:"", role:"", personality:"", family:"", appearance:"", hair:"", wardrobe:"", accessories:"" });
  useEffect(() => { if (!selectedId && cast.data?.cast[0]) setSelectedId(cast.data.cast[0].id); }, [cast.data, selectedId]);
  if (cast.loading || brands.loading) return <LoadState label="Loading Cast"/>;
  if (cast.error) return <ErrorState message={cast.error} onRetry={cast.refresh}/>;
  const list = cast.data?.cast ?? []; const selected = list.find((item) => item.id === selectedId) ?? null;
  async function createCharacter(){ if(!form.name.trim())return;setBusy(true);setError("");try{const result=await studioMutation<{castMemberId:string}>("/api/v1/studio/cast","POST",{name:form.name.trim(),identityKey:`${form.name.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"character"}-${crypto.randomUUID().slice(0,8)}`,brandId:form.brandId||null,identity:{role:form.role.trim()||null,personality:form.personality.trim()||null,family:form.family.trim()||null,appearance:form.appearance.trim()||null,hair:form.hair.trim()||null,wardrobe:form.wardrobe.trim()||null,accessories:form.accessories.trim()||null}});setSelectedId(result.castMemberId);setCreating(false);setForm({name:"",brandId:"",role:"",personality:"",family:"",appearance:"",hair:"",wardrobe:"",accessories:""});cast.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Character could not be created.");}finally{setBusy(false);}}
  return <>{!list.length ? <div className="sf-empty"><h2>No characters yet.</h2><p>Create a reusable character identity for future productions. Performance remains directed by each production.</p><button className="sf-primary" onClick={()=>setCreating(true)}>Create character</button></div> : <div className="sf-desk-layout"><aside className="sf-record-list" aria-label="Cast profiles"><button className="sf-record-create" onClick={()=>setCreating(true)}>＋ New character</button>{list.map((item)=><button key={item.id} className={selectedId===item.id?"active":""} onClick={()=>setSelectedId(item.id)}><strong>{item.name}</strong><small>{item.brandId?"Brand-linked character":"Reusable character"}</small></button>)}</aside>{selected?<div className="sf-record-detail"><div className="sf-profile-head"><span>Character profile</span><h2>{selected.name}</h2><p>This profile stores stable identity. Scene performance is directed from the current production, not frozen here.</p><dl className="sf-profile-facts"><div><dt>Identity</dt><dd>{selected.identityKey}</dd></div><div><dt>Brand</dt><dd>{brands.data?.brands.find((b)=>b.id===selected.brandId)?.name||"Independent"}</dd></div></dl></div><MemoryPanel scope="CAST" scopeRefId={selected.id} title="Character memory" description="Use this for identity, appearance, wardrobe, role and personality continuity — not poses or scene choreography."/></div>:null}</div>}
  {creating?<div className="sf-dialog-backdrop"><section className="sf-dialog sf-dialog-wide" role="dialog" aria-modal="true" aria-label="Create character"><button className="sf-dialog-close" onClick={()=>setCreating(false)}>×</button><span>Assets · Cast</span><h2>Create character</h2><div className="sf-form-grid"><label>Name<input value={form.name} onChange={(e)=>setForm({...form,name:e.currentTarget.value})}/></label><label>Brand<select value={form.brandId} onChange={(e)=>setForm({...form,brandId:e.currentTarget.value})}><option value="">No Brand</option>{(brands.data?.brands??[]).map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Role<input value={form.role} onChange={(e)=>setForm({...form,role:e.currentTarget.value})} placeholder="Presenter, customer, manager…"/></label><label>Personality<input value={form.personality} onChange={(e)=>setForm({...form,personality:e.currentTarget.value})} placeholder="Warm, dry, energetic…"/></label><label>Character family<input value={form.family} onChange={(e)=>setForm({...form,family:e.currentTarget.value})} placeholder="Optional morphology/family"/></label><label>Hair<input value={form.hair} onChange={(e)=>setForm({...form,hair:e.currentTarget.value})}/></label><label className="wide">Appearance<textarea rows={3} value={form.appearance} onChange={(e)=>setForm({...form,appearance:e.currentTarget.value})}/></label><label>Wardrobe<textarea rows={3} value={form.wardrobe} onChange={(e)=>setForm({...form,wardrobe:e.currentTarget.value})}/></label><label>Accessories<textarea rows={3} value={form.accessories} onChange={(e)=>setForm({...form,accessories:e.currentTarget.value})}/></label></div>{error?<p className="sf-inline-error">{error}</p>:null}<div className="sf-dialog-actions"><button className="sf-secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="sf-primary" disabled={busy||!form.name.trim()} onClick={createCharacter}>Create character</button></div></section></div>:null}</>;
}

export function AssetsRoute(){const[tab,setTab]=useState<"files"|"cast">("files");return <section className="sf-route"><header className="sf-route-head"><div><span>Assets</span><h1>Files and Cast.</h1><p>Reusable source material and stable character identities, kept close to production.</p></div></header><div className="sf-tabs" role="tablist" aria-label="Assets"><button role="tab" aria-selected={tab==="files"} className={tab==="files"?"active":""} onClick={()=>setTab("files")}>Files</button><button role="tab" aria-selected={tab==="cast"} className={tab==="cast"?"active":""} onClick={()=>setTab("cast")}>Cast</button></div>{tab==="files"?<FilesView/>:<CastView/>}</section>}
