import { useEffect, useMemo, useState } from "react";
import { useStudioBrands, useStudioSeries } from "../hooks.js";
import { studioMutation } from "../api.js";
import { ErrorState, LoadState } from "./shared.js";
import { MemoryPanel } from "./MemoryPanel.js";
import { PRODUCTION_REGISTRY, type FamilyId } from "@/studio-v1/public/registry";

const FAMILY_TO_DOMAIN: Record<FamilyId,"EXPLAINER"|"WHITEBOARD"|"STICKMAN"|"EDITORIAL_MOTION">={explainer:"EXPLAINER",whiteboard:"WHITEBOARD",stickman:"STICKMAN","editorial-motion":"EDITORIAL_MOTION"};
export function SeriesRoute({onOpenProject}:{onOpenProject:(id:string)=>void}){
 const series=useStudioSeries();const brands=useStudioBrands();const[selectedId,setSelectedId]=useState<string|null>(null);const[creating,setCreating]=useState(false);const[nextOpen,setNextOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const[form,setForm]=useState({name:"",description:"",brandId:"",premise:"",pillars:"",continuity:"",opener:"",closer:"",sound:""});
 const publicTypes=useMemo(()=>PRODUCTION_REGISTRY.videoTypes.filter((item)=>item.publicEnabled&&item.capabilityContract.verification.status==="verified"),[]);const[next,setNext]=useState({videoType:"",prompt:"",duration:"60",ratio:"16:9"});
 useEffect(()=>{if(!selectedId&&series.data?.series[0])setSelectedId(series.data.series[0].id)},[series.data,selectedId]);useEffect(()=>{if(!next.videoType&&publicTypes[0])setNext(v=>({...v,videoType:publicTypes[0].id}))},[next.videoType,publicTypes]);
 if(series.loading||brands.loading)return <LoadState label="Loading Series"/>;if(series.error)return <ErrorState message={series.error} onRetry={series.refresh}/>;const list=series.data?.series??[];const selected=list.find(s=>s.id===selectedId)??null;
 async function createSeries(){if(!form.name.trim())return;setBusy(true);setError("");try{const result=await studioMutation<{seriesId:string}>("/api/v1/studio/series","POST",{name:form.name.trim(),description:form.description.trim()||null,brandId:form.brandId||null,bible:{premise:form.premise.trim()||null,contentPillars:form.pillars.split(/\n|,/).map(x=>x.trim()).filter(Boolean),continuityRules:form.continuity.split("\n").map(x=>x.trim()).filter(Boolean),signatureOpener:form.opener.trim()||null,signatureCloser:form.closer.trim()||null,soundAndVoice:form.sound.trim()||null}});setSelectedId(result.seriesId);setCreating(false);series.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Series could not be created.");}finally{setBusy(false)}}
 async function createNext(){if(!selected||!next.videoType||!next.prompt.trim())return;const type=publicTypes.find(v=>v.id===next.videoType);if(!type)return;setBusy(true);setError("");try{const result=await studioMutation<{productionId:string}>(`/api/v1/studio/series/${selected.id}/next-episode`,"POST",{family:FAMILY_TO_DOMAIN[type.family],videoType:type.id,prompt:next.prompt.trim(),duration:Number(next.duration)||60,aspectRatio:next.ratio});setNextOpen(false);onOpenProject(result.productionId);}catch(reason){setError(reason instanceof Error?reason.message:"Next episode could not be created.");}finally{setBusy(false)}}
 return <section className="sf-route"><header className="sf-route-head"><div><span>Series</span><h1>Continuity without repetition.</h1><p>Keep a Series Bible and completed-episode history while every new film remains a fresh production.</p></div><button className="sf-primary" onClick={()=>setCreating(true)}>New Series</button></header>{!list.length?<div className="sf-empty"><h2>No Series yet.</h2><p>Create one when multiple productions should share characters, rules and continuity.</p><button className="sf-primary" onClick={()=>setCreating(true)}>Create Series</button></div>:<div className="sf-desk-layout"><aside className="sf-record-list" aria-label="Series">{list.map(item=><button key={item.id} className={selectedId===item.id?"active":""} onClick={()=>setSelectedId(item.id)}><strong>{item.name}</strong><small>{item.episodes.length?`${item.episodes.length} episode${item.episodes.length===1?"":"s"}`:"No episodes yet"}</small></button>)}</aside>{selected?<div className="sf-record-detail"><div className="sf-profile-head sf-profile-with-action"><div><span>Series</span><h2>{selected.name}</h2><p>{selected.description||"No description saved."}</p></div><button className="sf-primary" onClick={()=>setNextOpen(true)} disabled={!publicTypes.length}>Next episode</button></div>{!publicTypes.length?<p className="sf-cert-note">Next-episode production is ready, but no production type is currently certified for public use. The desk will expose it automatically when the registry enables one.</p>:null}<section className="sf-episode-section"><div className="sf-section-head"><div><span>Episodes</span><h2>Production history</h2></div></div>{selected.episodes.length?<div className="sf-episode-list">{[...selected.episodes].sort((a,b)=>b.episodeOrdinal-a.episodeOrdinal).map(ep=><button key={ep.id} onClick={()=>onOpenProject(ep.productionId)}><span>Episode {ep.episodeOrdinal}</span><strong>{ep.title||"Open production"}</strong><small>{new Date(ep.createdAt).toLocaleDateString()}</small></button>)}</div>:<p className="sf-muted">No completed or in-progress episodes are bound to this Series yet.</p>}</section><MemoryPanel scope="SERIES" scopeRefId={selected.id} title="Series Bible" description="Continuity rules, recurring treatment, covered topics and future-episode memory live here. Completed Film Memory remains immutable."/></div>:null}</div>}
 {creating?<div className="sf-dialog-backdrop"><section className="sf-dialog sf-dialog-wide" role="dialog" aria-modal="true" aria-label="Create Series"><button className="sf-dialog-close" onClick={()=>setCreating(false)}>×</button><span>Series</span><h2>Create Series</h2><div className="sf-form-grid"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.currentTarget.value})}/></label><label>Brand<select value={form.brandId} onChange={e=>setForm({...form,brandId:e.currentTarget.value})}><option value="">No Brand</option>{(brands.data?.brands??[]).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="wide">Description<textarea rows={2} value={form.description} onChange={e=>setForm({...form,description:e.currentTarget.value})}/></label><label className="wide">Series premise<textarea rows={3} value={form.premise} onChange={e=>setForm({...form,premise:e.currentTarget.value})}/></label><label>Content pillars<textarea rows={4} value={form.pillars} onChange={e=>setForm({...form,pillars:e.currentTarget.value})} placeholder="One per line"/></label><label>Continuity rules<textarea rows={4} value={form.continuity} onChange={e=>setForm({...form,continuity:e.currentTarget.value})} placeholder="One per line"/></label><label>Signature opener<input value={form.opener} onChange={e=>setForm({...form,opener:e.currentTarget.value})}/></label><label>Signature closer<input value={form.closer} onChange={e=>setForm({...form,closer:e.currentTarget.value})}/></label><label className="wide">Voice / sound treatment<textarea rows={3} value={form.sound} onChange={e=>setForm({...form,sound:e.currentTarget.value})}/></label></div>{error?<p className="sf-inline-error">{error}</p>:null}<div className="sf-dialog-actions"><button className="sf-secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="sf-primary" disabled={busy||!form.name.trim()} onClick={createSeries}>Create Series</button></div></section></div>:null}
 {nextOpen&&selected?<div className="sf-dialog-backdrop"><section className="sf-dialog" role="dialog" aria-modal="true" aria-label="Create next episode"><button className="sf-dialog-close" onClick={()=>setNextOpen(false)}>×</button><span>{selected.name}</span><h2>Create next episode</h2><p>The next ordinal is reserved atomically when this production is created.</p><label>Production type<select value={next.videoType} onChange={e=>setNext({...next,videoType:e.currentTarget.value})}>{publicTypes.map(type=><option key={type.id} value={type.id}>{PRODUCTION_REGISTRY.families.find(f=>f.id===type.family)?.name} · {type.name}</option>)}</select></label><label>Brief<textarea rows={5} value={next.prompt} onChange={e=>setNext({...next,prompt:e.currentTarget.value})} placeholder="What should this episode achieve?"/></label><div className="sf-form-grid"><label>Length<select value={next.duration} onChange={e=>setNext({...next,duration:e.currentTarget.value})}><option>30</option><option>45</option><option>60</option></select></label><label>Format<select value={next.ratio} onChange={e=>setNext({...next,ratio:e.currentTarget.value})}><option>16:9</option><option>9:16</option><option>1:1</option></select></label></div>{error?<p className="sf-inline-error">{error}</p>:null}<div className="sf-dialog-actions"><button className="sf-secondary" onClick={()=>setNextOpen(false)}>Cancel</button><button className="sf-primary" disabled={busy||!next.prompt.trim()||!next.videoType} onClick={createNext}>Create episode</button></div></section></div>:null}
 </section>;
}
