#!/usr/bin/env python3
from __future__ import annotations
import json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def txt(path:str)->str:return (ROOT/path).read_text(errors='ignore')
checks=[]
def add(name,ok,detail=''):checks.append({'name':name,'ok':bool(ok),'detail':detail})

schema=txt('prisma/schema.prisma')
core=txt('src/studio-v1/architecture/core.ts')
lineage=txt('src/studio-v1/architecture/lineage.ts')
durability=txt('src/studio-v1/architecture/workflow-durability.ts')
worker=txt('scripts/studio-worker.ts')
billing=txt('src/studio-v1/billing.ts')
revisions=txt('src/studio-v1/revisions.ts')
finalout=txt('src/studio-v1/production-engines/workflow.ts')
nexmind=txt('src/studio-v1/nexmind-p8/workflow.ts')
review=txt('app/api/v1/productions/[id]/review/route.ts')
claim=txt('app/api/v1/studio/production-drafts/[id]/claim/route.ts')
prodroute=txt('app/api/v1/studio/productions/route.ts')
gov=txt('src/lib/studio-governance.ts')
statecore=txt('src/lib/studio-production-draft-core.ts')
migration=txt('prisma/migrations/20260814133000_studio_public_architecture_core/migration.sql')

families=re.search(r'enum StudioProductionFamily\s*\{([^}]*)\}',schema,re.S)
family_set=set(re.findall(r'\b[A-Z][A-Z_]+\b',families.group(1) if families else ''))
add('Exactly four production families remain canonical',family_set=={'EXPLAINER','WHITEBOARD','STICKMAN','EDITORIAL_MOTION'},repr(sorted(family_set)))
add('Production is canonical lifecycle authority','studioState        StudioProductionState' in schema and 'stateVersion' in schema and 'lastStateChangedAt' in schema)
add('Claim promotes the same stable Draft id into canonical Production','syncClaimedDraftToCanonicalProduction(draft)' in claim and 'id: draft.id' in core)
add('Browser list reads Production state before Draft compatibility mirror','state: production?.studioState ?? draft.studioState' in prodroute)
add('State transitions are immutable audit rows','model StudioStateTransition' in schema and 'studioStateTransition.create' in core and 'sequence: (last._max.sequence ?? 0) + 1' in core)
add('Clarification transition PLANNING -> DRAFT is first-class',re.search(r'PLANNING:\s*\[[^\]]*"DRAFT"',statecore,re.S) is not None)
add('Source relationships are owner-scoped before relational binding','ownedSourceIds' in core and 'ownerUserId: draft.ownerId' in core and 'sourceId: source.id && ownedSourceIds.has(source.id)' in core)
add('Paid production input is immutably snapshotted','StudioPaidInputLineageV1' in lineage and 'snapshotType: "PAID_INPUT"' in lineage and 'capturePaidInputLineageTx' in billing)
add('Revision input is immutably snapshotted','snapshotType: "REVISION_INPUT"' in revisions and 'StudioRevisionInputLineageV1' in revisions)
add('Final output lineage binds input, entitlement, Creative Lock, execution and output',all(x in finalout for x in ['inputSnapshot:{','entitlement:{','creativeLock:{','execution:{','output:{','lineageHash=canonicalHash']))
add('ProductionVersion stores direct lineage identifiers',all(x in schema for x in ['workflowRunId','entitlementId','quoteId','inputSnapshotId','creativeLockArtifactId','outputSha256','lineageHash']))
add('ProductionVersion number allocation occurs under canonical Production row lock','allocateProductionVersionNumberTx(tx,run.productionId)' in finalout and finalout.index('allocateProductionVersionNumberTx(tx,run.productionId)')>finalout.index('prisma.$transaction(async(tx)=>'))
add('Final object keys are retry-stable project-version/content addressed','final/project-v${run.projectVersion}/output-${outputSha256}.mp4' in finalout)
add('Final output retries reuse the same lineage version','productionVersion.findUnique({where:{lineageHash}})' in finalout and 'if(existing)return existing' in finalout and 'output-${outputSha256}.mp4' in finalout)
add('Artifact writes are content-addressed and idempotent','canonicalHash(input.content)' in gov and 'productionId_projectVersion_artifactType_contentHash' in gov and 'P2002' in gov)
add('Workflow events are content-idempotent and sequence allocation is serialized','idempotencyKey = canonicalHash' in durability and 'FOR UPDATE' in durability and 'studioWorkflowEvent.findUnique' in durability)
add('Activities use leases, heartbeat and stale RUNNING recovery',all(x in durability for x in ['leaseExpiresAt','recoverExpiredStudioActivityLeases','heartbeatAt','recoveryCount']))
add('Worker identity cannot repeat on normal process restart','randomUUID()' in worker and 'studio-worker-${process.pid}-${randomUUID()}' in worker)
add('Only the current worker claimant can commit/complete','assertStudioActivityLeaseTx' in durability and 'claimedBy !== workerId' in durability and 'completeStudioActivity(activity.id,activity.workerId' in finalout and 'assertStudioActivityLeaseTx(tx,activity.id,activity.workerId)' in finalout)
add('Durable successor work is queued before predecessor completion',nexmind.index('queueStandaloneFamilyReviewEvidence') < nexmind.index('completeStudioActivity(activity.id, activity.workerId', nexmind.index('export async function runStandaloneNexMindP8Activity')) and nexmind.index('queueReviewedFinalOutputPromotion', nexmind.index('export async function runFinalizeStandaloneNexMindP8Activity')) < nexmind.index('completeStudioActivity(activity.id, activity.workerId', nexmind.index('export async function runFinalizeStandaloneNexMindP8Activity')))
add('Atomic purchase binds debit + entitlement + durable workflow and canonical PRODUCTION state',all(x in billing for x in ['STUDIO_PRODUCTION_DEBIT','studioProductionEntitlement.create','studioWorkflowRun.create','transitionCanonicalStudioStateTx','isolationLevel: "Serializable"']))
add('Entitlement has unique workflow binding','workflowRunId          String? @unique @db.Uuid' in schema and 'data: { workflowRunId: workflow.id }' in billing)
add('Low balance is a state transition without debit',billing.index('to: "INSUFFICIENT_BALANCE"', billing.index('if (account.balanceMinor < quote.finalAmountMinor)')) < billing.index('tx.studioLedgerEntry.create', billing.index('if (account.balanceMinor < quote.finalAmountMinor)')))
add('Revision uses same entitlement and no new debit','PAID_ENTITLEMENT_REQUIRED_FOR_REVISION' in revisions and 'secondCharge: false' in revisions and 'STUDIO_PRODUCTION_DEBIT' not in revisions)
add('Revision records FINAL_REVIEW -> REVISION_REQUESTED -> PRODUCTION','to: "REVISION_REQUESTED"' in revisions and 'to: "PRODUCTION"' in revisions)
add('Customer approval records canonical FINAL_REVIEW -> COMPLETE','current.studioState!=="FINAL_REVIEW"' in review and 'to:"COMPLETE"' in review)
add('Trusted Studio flows no longer directly write Draft studioState outside canonical mirror',not any('draft.update' in t and 'studioState' in t for t in [billing,revisions,finalout,nexmind,review]))
add('Architecture migration backfills canonical Production state from Draft','UPDATE "productions" AS p' in migration and 'SET "studioState" = d."studioState"' in migration)
add('Migration adds lineage/source/audit/durability persistence',all(x in migration for x in ['studio_production_inputs','studio_lineage_snapshots','studio_state_transitions','leaseExpiresAt','idempotencyKey','lineageHash']))
add('Migration includes relational integrity for output lineage',all(x in migration for x in ['production_versions_workflowRunId_fkey','production_versions_entitlementId_fkey','production_versions_quoteId_fkey','production_versions_inputSnapshotId_fkey','production_versions_creativeLockArtifactId_fkey']))
add('No browser-authored price is accepted in purchase service','clientPrice' not in billing and 'finalAmountMinor' in billing and 'approvedDurationSeconds' in billing)
add('Owner-scoped audit loader exists',(ROOT/'src/studio-v1/architecture/audit.ts').exists() and 'ownerUserId:userId' in txt('src/studio-v1/architecture/audit.ts'))

report={'schema':'StudioPublicArchitectureCoreQA V1','implementationPass':all(c['ok'] for c in checks),'checks':checks,'passed':sum(c['ok'] for c in checks),'total':len(checks),'deploymentCertificationPass':False,'deploymentCertificationNote':'Requires dependency-complete Node >=24 + Prisma 7 schema/migration validation against a real PostgreSQL staging database.'}
(ROOT/'reports').mkdir(exist_ok=True)
(ROOT/'reports/STUDIO_PUBLIC_ARCHITECTURE_CORE_QA.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
raise SystemExit(0 if report['implementationPass'] else 1)
