#!/usr/bin/env python3
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def txt(p): return (ROOT/p).read_text(errors='ignore')
checks=[]
def add(name,ok,detail=''): checks.append({'name':name,'ok':bool(ok),'detail':detail})
schema=txt('prisma/schema.prisma'); contracts=txt('src/studio-v1/memory/contracts.ts'); policies=txt('src/studio-v1/memory/policies.ts'); service=txt('src/studio-v1/memory/service.ts'); resolver=txt('src/studio-v1/memory/resolver.ts'); prodmem=txt('src/studio-v1/memory/production-input.ts'); nx=txt('src/studio-v1/nexmind-p8/workflow.ts'); final=txt('src/studio-v1/production-engines/workflow.ts'); migration=txt('prisma/migrations/20260814151000_studio_creative_memory_brand_cast_series/migration.sql'); prodroute=txt('app/api/v1/productions/[id]/memory/route.ts'); memoryroute=txt('app/api/v1/studio/memory/route.ts'); memoryitem=txt('app/api/v1/studio/memory/[id]/route.ts'); brandroute=txt('app/api/v1/studio/brands/route.ts'); castroute=txt('app/api/v1/studio/cast/route.ts'); seriesroute=txt('app/api/v1/studio/series/route.ts')
family=re.search(r'enum StudioProductionFamily\s*\{([^}]*)\}',schema,re.S); fam=set(re.findall(r'\b[A-Z][A-Z_]+\b',family.group(1) if family else ''))
add('Exactly four production families remain canonical',fam=={'EXPLAINER','WHITEBOARD','STICKMAN','EDITORIAL_MOTION'},repr(sorted(fam)))
add('Series is not a fifth production family','SERIES' not in fam and 'productionFamily:false' in seriesroute)
add('Five explicit memory scopes exist',all(x in schema for x in ['ACCOUNT','BRAND','CAST','SERIES','PRODUCTION']) and 'enum StudioMemoryScope' in schema)
add('Every memory item has owner, scope, scopeRef, key and current version',all(x in schema for x in ['model StudioMemoryItem','ownerUserId','scopeRefId','currentVersion']))
add('Memory versions are append-only numbered records',all(x in schema for x in ['model StudioMemoryVersion','versionNumber','@@unique([memoryItemId, versionNumber])']))
add('Effective state is explicit',all(x in schema for x in ['StudioMemoryEffectiveState','ACTIVE','INACTIVE','DELETED']))
add('Temporal effectiveness is explicit',all(x in schema for x in ['effectiveFrom','effectiveUntil','effectiveFromEpisodeOrdinal','effectiveUntilEpisodeOrdinal']))
add('Provenance is mandatory persisted JSON','provenance            Json' in schema and 'StudioMemoryProvenance' in contracts)
add('Customer edits append a version rather than overwrite content','appendStudioMemoryVersion' in memoryitem and 'studioMemoryVersion.create' in service)
add('Customer deletion is a tombstone, not history deletion','tombstoneStudioMemory' in memoryitem and 'effectiveState: "DELETED"' in service and 'studioMemoryVersion.delete' not in service)
add('Brand is a stable production authority resource','model StudioBrand' in schema and 'BRAND_AUTHORITY' in brandroute and 'BINDING_UNLESS_EXPLICIT_PRODUCTION_EXCEPTION' in contracts)
add('Cast is stored under Assets namespace','assetNamespace String     @default("CAST")' in schema and 'assetNamespace:"CAST"' in castroute)
add('Cast identity key is stable','identityKey' in schema and '@@unique([ownerUserId, identityKey])' in schema)
add('Cast performance trajectories are stripped from identity',all(x in policies for x in ['jointAngles','trajectory','keyframes','stripPerformanceState']))
add('V5.1 is exact performance authority','NexPerformanceUnifiedV5@5.1.0-skin-safe-angular-continuity' in contracts and '64056fed5b4354e13fe945f71e0fa2f88db68d2be2b146bc3d1bc61d21844ef3' in contracts)
add('Series has explicit ordered episode continuity','model StudioSeriesEpisode' in schema and '@@unique([seriesId, episodeOrdinal])' in schema)
add('Series history only consumes completed prior episodes','episodeOrdinal: { lt: episodeOrdinal }' in resolver and 'studioState: "COMPLETE"' in resolver)
add('Anti-repetition uses explicit plan signature dimensions',all(x in policies for x in ['environments','silhouettes','transitions','cameras','actorPositions','headlineStructures','visualMetaphors','motifs']))
add('Continuity can justify intentional repetition','continuityReasons' in policies and 'REPETITION_REQUIRES_CONTINUITY_REASON_OR_RANKED_ALTERNATIVE' in policies)
add('Production can bind Brand and Series without taxonomy change','brandId' in schema and 'seriesId' in schema and 'model Production {' in schema)
add('Production can bind stable reusable Cast members','model StudioProductionCastMember' in schema and 'studioCastLinks' in schema)
add('This-production-only write mode is implemented','THIS_PRODUCTION_ONLY' in contracts and 'scope="PRODUCTION";scopeRefId=id' in prodroute)
add('Remember-for-Brand write mode is implemented','REMEMBER_FOR_BRAND' in contracts and 'scope="BRAND"' in prodroute)
add('Remember-for-Series write mode is implemented','REMEMBER_FOR_SERIES' in contracts and 'scope="SERIES"' in prodroute)
add('Update-character-going-forward is implemented','UPDATE_CHARACTER_GOING_FORWARD' in contracts and 'targetCastMemberId' in prodroute)
add('Future-episode effective update is implemented','UPDATE_FROM_FUTURE_EPISODE' in contracts and 'effectiveFromEpisodeOrdinal=write.futureEpisodeOrdinal' in prodroute)
add('Memory inspection API exposes history','inspectStudioMemory' in memoryroute and 'include: { versions:' in service)
add('Production start freezes immutable MEMORY_INPUT snapshot','captureProductionMemoryInputSnapshot' in nx and 'snapshotType: "MEMORY_INPUT"' in prodmem)
add('P8 receives persistent memory through existing request contract','persistentMemory: memoryPacket' in nx and 'brandAuthority: record(memoryPacket.brandAuthority)' in nx and 'seriesMemory: record(memoryPacket.seriesMemory)' in nx)
add('Final output requires exact frozen memory snapshot','PRODUCTION_MEMORY_INPUT_LINEAGE_MISSING' in final and 'PRODUCTION_MEMORY_INPUT_LINEAGE_MISMATCH' in final)
add('ProductionVersion directly binds memory snapshot',all(x in schema for x in ['memoryInputSnapshotId','memoryInputSnapshotHash','ProductionVersionMemoryInputSnapshot']))
add('Final lineage hash includes memory input snapshot','memoryInputSnapshot:{id:memoryInputLineage.id' in final)
add('Source hash includes memory input hash','memory:memoryInputLineage.contentHash' in final)
add('Final production emits structured FILM_MEMORY','captureFilmMemorySnapshotTx' in final and 'StudioFilmMemoryV1' in prodmem and 'snapshotType: "FILM_MEMORY"' in prodmem)
add('Film Memory has required canonical state categories',all(x in prodmem for x in ['whatHasBeenShown','audienceLearned','persistentObjects','unresolvedNarrativePromises','usedVisualMetaphors','previousCameraGrammar','motifEvolution','intensityCurve','settledSceneState']))
add('Completed production history cannot follow mutable memory','memoryInputSnapshotId' in final and 'IMMUTABLE_MEMORY_INPUT_SNAPSHOT_PER_PROJECT_VERSION' in nx)
add('Migration creates all persistent memory tables',all(x in migration for x in ['studio_brands','studio_cast_members','studio_series','studio_series_episodes','studio_memory_items','studio_memory_versions','studio_memory_snapshots','studio_production_cast_members']))
add('Migration adds relational integrity for Brand/Series/Cast/memory snapshot',all(x in migration for x in ['productions_brandId_fkey','productions_seriesId_fkey','studio_production_cast_members_castMemberId_fkey','production_versions_memoryInputSnapshotId_fkey']))
add('Generic scope ownership is enforced before memory write','assertScopeOwnership' in service and 'MEMORY_SCOPE_NOT_OWNED' in service)
add('No browser-authored memory may target another owner',all(x in service for x in ['ownerUserId','findFirst']) and 'auth.session!.userId' in prodroute)
report={'schema':'StudioCreativeMemoryBrandCastSeriesQA V1','implementationPass':all(x['ok'] for x in checks),'passed':sum(x['ok'] for x in checks),'total':len(checks),'checks':checks,'deploymentCertificationPass':False,'deploymentCertificationNote':'Implementation/static/domain tests pass here. Deployment still requires the Architecture Core Node >=24 + Prisma 7 dependency-complete schema validation and migration execution against PostgreSQL staging.'}
(ROOT/'reports').mkdir(exist_ok=True)
(ROOT/'reports/MEMORY_ARCHITECTURE_QA.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
raise SystemExit(0 if report['implementationPass'] else 1)
