import { getPrisma } from "../src/lib/db";
import { deleteObject, writeObject } from "../src/lib/object-storage";

function jsonSafe(value:unknown){return JSON.parse(JSON.stringify(value,(_,v)=>typeof v==="bigint"?v.toString():v));}
async function cleanupExpiredExports(){const prisma=getPrisma();if(!prisma)throw new Error("DATABASE_REQUIRED");const rows=await prisma.accountDataRequest.findMany({where:{type:"EXPORT",status:"COMPLETE",expiresAt:{lt:new Date()},objectKey:{not:null}},select:{id:true,objectKey:true}});for(const row of rows){if(row.objectKey)await deleteObject(row.objectKey).catch(()=>undefined);await prisma.accountDataRequest.update({where:{id:row.id},data:{status:"EXPIRED",objectKey:null}});}return rows.length;}
async function processOne(){const prisma=getPrisma();if(!prisma)throw new Error("DATABASE_REQUIRED");const request=await prisma.accountDataRequest.findFirst({where:{status:"QUEUED"},orderBy:{requestedAt:"asc"}});if(!request)return false;const claim=await prisma.accountDataRequest.updateMany({where:{id:request.id,status:"QUEUED"},data:{status:"RUNNING",failureReason:null}});if(claim.count!==1)return true;try{
  if(request.type==="EXPORT"){
    const [user,productions,sources,brands,cast,series,memory,ledger,funding,notifications,sessions,identities,audit]=await Promise.all([
      prisma.user.findUnique({where:{id:request.userId},select:{id:true,email:true,displayName:true,avatarUrl:true,settings:true,privacyStatus:true,createdAt:true,updatedAt:true}}),
      prisma.production.findMany({where:{ownerUserId:request.userId},include:{versions:true,studioStateTransitions:true}}),
      prisma.source.findMany({where:{ownerUserId:request.userId}}),prisma.studioBrand.findMany({where:{ownerUserId:request.userId}}),prisma.studioCastMember.findMany({where:{ownerUserId:request.userId}}),prisma.studioSeries.findMany({where:{ownerUserId:request.userId},include:{episodes:true}}),prisma.studioMemoryItem.findMany({where:{ownerUserId:request.userId},include:{versions:true}}),prisma.studioLedgerEntry.findMany({where:{userId:request.userId},orderBy:{createdAt:"asc"}}),prisma.studioFundingIntent.findMany({where:{userId:request.userId},orderBy:{createdAt:"asc"}}),prisma.studioNotification.findMany({where:{userId:request.userId},orderBy:{createdAt:"asc"}}),prisma.session.findMany({where:{userId:request.userId},select:{id:true,status:true,userAgent:true,expiresAt:true,lastSeenAt:true,revokedAt:true,createdAt:true}}),prisma.authIdentity.findMany({where:{userId:request.userId},select:{provider:true,subject:true,email:true,emailVerified:true,createdAt:true,updatedAt:true}}),prisma.auditEvent.findMany({where:{actorUserId:request.userId},select:{action:true,entityType:true,entityId:true,requestId:true,createdAt:true},orderBy:{createdAt:"asc"}})
    ]);
    const payload=jsonSafe({exportVersion:"studio-account-export-v1",generatedAt:new Date().toISOString(),user,productions,sources:sources.map(({objectKey,quarantineObjectKey,...rest})=>({...rest,storedObjectPresent:Boolean(objectKey),quarantinedObjectPresent:Boolean(quarantineObjectKey)})),brands,cast,series,memory,billing:{ledger:ledger.map(({externalReference,...rest})=>({...rest,externalReference:externalReference?"REDACTED":null})),funding:funding.map(({providerReference,providerCheckoutUrl,...rest})=>({...rest,providerReference:providerReference?"REDACTED":null,providerCheckoutUrl:null}))},notifications,sessions,identities,audit});
    const objectKey=`account-exports/${request.userId}/${request.id}.json`;await writeObject(objectKey,JSON.stringify(payload,null,2),{contentType:"application/json"});await prisma.accountDataRequest.update({where:{id:request.id},data:{status:"COMPLETE",objectKey,completedAt:new Date(),expiresAt:new Date(Date.now()+7*86400000)}});return true;
  }
  if(request.type==="DELETE"){
    const account=await prisma.studioCreditAccount.findUnique({where:{userId:request.userId}});if((account?.balanceMinor??0)>0){await prisma.accountDataRequest.update({where:{id:request.id},data:{status:"ACTION_REQUIRED",failureReason:"BALANCE_RESOLUTION_REQUIRED"}});return true;}
    const [sources,versions,exports]=await Promise.all([prisma.source.findMany({where:{ownerUserId:request.userId},select:{objectKey:true,quarantineObjectKey:true}}),prisma.productionVersion.findMany({where:{production:{ownerUserId:request.userId}},select:{compositionObjectKey:true,previewObjectKey:true,outputObjectKey:true,thumbnailObjectKey:true}}),prisma.accountDataRequest.findMany({where:{userId:request.userId,type:"EXPORT",objectKey:{not:null}},select:{id:true,objectKey:true}})]);
    const keys=new Set<string>();for(const row of sources)for(const key of [row.objectKey,row.quarantineObjectKey])if(key)keys.add(key);for(const row of versions)for(const key of [row.compositionObjectKey,row.previewObjectKey,row.outputObjectKey,row.thumbnailObjectKey])if(key)keys.add(key);for(const row of exports)if(row.objectKey)keys.add(row.objectKey);for(const key of keys)await deleteObject(key);await prisma.accountDataRequest.updateMany({where:{userId:request.userId,type:"EXPORT"},data:{status:"EXPIRED",objectKey:null,expiresAt:new Date()}});
    const deletingUser=await prisma.user.findUnique({where:{id:request.userId},select:{email:true}});
    await prisma.$transaction(async tx=>{
      await tx.session.deleteMany({where:{userId:request.userId}});await tx.authChallenge.deleteMany({where:{OR:[{userId:request.userId},...(deletingUser?.email?[{identifier:deletingUser.email.toLowerCase()}]:[])]}});await tx.authIdentity.deleteMany({where:{userId:request.userId}});await tx.assetDeliveryTicket.deleteMany({where:{userId:request.userId}});await tx.studioNotification.deleteMany({where:{userId:request.userId}});await tx.source.deleteMany({where:{ownerUserId:request.userId}});await tx.studioMemoryItem.deleteMany({where:{ownerUserId:request.userId}});await tx.production.deleteMany({where:{ownerUserId:request.userId}});await tx.studioCastMember.deleteMany({where:{ownerUserId:request.userId}});await tx.studioSeries.deleteMany({where:{ownerUserId:request.userId}});await tx.studioBrand.deleteMany({where:{ownerUserId:request.userId}});
      await tx.auditEvent.create({data:{actorUserId:request.userId,action:"ACCOUNT_DELETION_COMPLETED",entityType:"User",entityId:request.userId,requestId:`account-delete:${request.id}`,after:{financialRecordsRetained:true} as any}});await tx.user.update({where:{id:request.userId},data:{email:null,displayName:"Deleted account",avatarUrl:null,settings:{},privacyStatus:"DELETED",deletedAt:new Date()}});await tx.accountDataRequest.update({where:{id:request.id},data:{status:"COMPLETE",failureReason:null,completedAt:new Date()}});
    });return true;
  }
  throw new Error("ACCOUNT_DATA_REQUEST_TYPE_UNSUPPORTED");
}catch(error){await prisma.accountDataRequest.update({where:{id:request.id},data:{status:"FAILED",failureReason:(error instanceof Error?error.message:"ACCOUNT_DATA_REQUEST_FAILED").slice(0,500),completedAt:new Date()}});return true;}}
(async()=>{await cleanupExpiredExports();while(await processOne()){}process.exit(0);})().catch(error=>{console.error(error);process.exit(1);});
