"use client";
import { useRouter } from "next/navigation";
import { PRODUCTION_REGISTRY } from "@/studio-v1/public/registry/production-family-registry";
import { getPublicVideoTypes } from "@/studio-v1/public/registry/selectors";

export function StudioWorkExperience({ authenticated }: { authenticated:boolean }) {
  const router=useRouter();
  const groups=PRODUCTION_REGISTRY.families.map((family)=>({family,items:getPublicVideoTypes(PRODUCTION_REGISTRY,family.id)}));
  const count=groups.reduce((n,group)=>n+group.items.length,0);
  return <div className="sv1-root sv1-calm"><header className="sv1-header"><button className="sv1-wordmark" onClick={()=>router.push("/")} aria-label="Studio home"><i aria-hidden="true">·</i><span>Studio</span></button><nav aria-label="Studio navigation"><button aria-current="page">Work</button><button onClick={()=>router.push("/pricing")}>Pricing</button><button onClick={()=>router.push(authenticated?"/dashboard":"/?signin=1")}>{authenticated?"Dashboard":"Sign in"}</button><button className="sv1-primary small" onClick={()=>router.push("/")}>Create</button></nav></header><main className="sv1-public-main sv1-editorial-page"><div className="sv1-section-head large"><p className="sv1-kicker">Work</p><h1>Finished films, not promises.</h1><p>Every film published here must come from the same production path customers use. No mockups, borrowed footage or staged marketing demos.</p></div>{count===0?<section className="sv1-release-state"><p className="sv1-kicker">Public gallery</p><h2>The gallery is intentionally empty.</h2><p>The public gallery opens with Studio-made films that meet the release standard. Until then, Studio leaves the space empty rather than borrowing footage or staging examples.</p><button className="sv1-primary" onClick={()=>router.push("/")}>Start from the Studio</button></section>:<div className="sv1-work-groups">{groups.filter((group)=>group.items.length).map(({family,items})=><section key={family.id}><div className="sv1-section-head"><p className="sv1-kicker">{family.name}</p><h2>{family.name} work</h2></div><div className="sv1-video-grid">{items.map((item)=><article key={item.id} className="sv1-work-card"><div className="sv1-certified-media"><video muted loop playsInline preload="metadata" poster={item.posterFrame || undefined} aria-label={`${item.name} certified Studio preview`}><source src={item.previewVideo!.src} type={item.previewVideo!.type || "video/mp4"}/></video></div><div><strong>{item.name}</strong><p>{item.shortDescription}</p></div></article>)}</div></section>)}</div>}</main></div>;
}
